### PR TITLE
Replaced PyYAML for ruamel.yaml in order to support YAML 1.2 syntax.

### PR DESCRIPTION
**Pull request by rtician**
Fixes # .

Changes proposed in this PR:
- Support YAML 1.2 syntax
- Fix raw values being converted to boolean

PyYAML uses the YAML 1.1 syntax, with leads to conversion issues for values like `no`, `n`, `off`, `y`, etc, all those values were converted to `True` or `False`.

This PR replace PyYAML for ruamel.yaml to fix this behavior. Also added a test explaining a use case.

### CODE REVIEW

**Comment by rtician** [comment]
Hi @RonnyPfannschmidt, can you take a look and let me know what you think?

**Review by RonnyPfannschmidt — APPROVED** [review]
Looking good, thanks,

I'll try to merge /release on the weekend

**Comment by rtician** [comment]
that would be nice, thank you

**Comment by rtician** [comment]
@RonnyPfannschmidt could you please create a release with this?

**Comment by RonnyPfannschmidt** [comment]
Will do, ill defer something i didn't get to get the fixup out

**Pull request merged**
