### PR TITLE
refactor openapi_spec_validator imports

### LINKED ISSUE #131: ImportError: cannot import name 'validate_v2_spec' from 'openapi_spec_validator'
## Expected Behaviour
Import works

### Minimal Example Spec
* Install prance and run a validation
* Install openapi_spec_validator 0.5.0

## Actual Behaviour
`cannot import name 'validate_v2_spec' from 'openapi_spec_validator'`

### PR DESCRIPTION
**Pull request by samdammers**
Fixes #131

Changes proposed in this PR:
- refactor imports to latest release https://github.com/p1c2u/openapi-spec-validator/releases/tag/0.5.0

### CODE REVIEW

**Review by jayvdb — APPROVED** [review]
WFM

**Comment by samdammers** [comment]
This change introduces a test failure I am still looking at:
`FAILED tests/test_backends.py::test_openapi_spec_validator_validate_failure - Failed: DID NOT RAISE <class 'prance.ValidationError'>`

Auto detection seems to work well, apart from this one.

Initially I set the validator explicitly, however that introduced numerous test failures related to minor versions of the openapi spec 

`FAILED tests/test_resolving_parser.py::test_issue_83_skip_propagation - prance.ValidationError: ("'3.0.3' does not match '^3\\\\.1\\\\.\\\\d+(-.+)?$'", 'pattern', deque(['openapi']), None, [], '^3\\.1\\.\\d+(-.+)?$', '3.0.3', {...`

**Comment by samdammers** [comment]
I believe the issue is in the latest openapi-spec-validator, specifically for the v2 validator
Raised https://github.com/p1c2u/openapi-spec-validator/issues/176

**Comment by samdammers** [comment]
https://github.com/p1c2u/openapi-spec-validator/pull/177 fixed, 
updating backend to openapi_spec_backend 0.5.1 and the test is passing :tada:

**Comment by robinmackaij-kadaster** [comment]
A release with this update / support for new openapi-spec-validator would be most welcome. Is there an ETA?

**Comment by samdammers** [comment]
@RonnyPfannschmidt if you have 10 mins free to review this PR, its quiet small and just keeps prance compatible with the latest openapi_spec_validator version

**Comment by RonnyPfannschmidt** [comment]
it looks like the most part of the if/else can be collapsed as its now the same

**Comment by samdammers** [comment]
It probably does actually, good point I'll pop that in shortly

**Comment by RonnyPfannschmidt** [comment]
i just fired up #136 as we do have a few more python versions these days, my impression form the failure is that we absolutely need a minimal dependency version for the openapi-spec lib

**Comment by samdammers** [comment]
Ok, locked to compatible release 0.5.1, and yeah ditched the majority of the if/else now the dep auto-detects version.

**Review by RonnyPfannschmidt — APPROVED** [review]
lovely, thanks

**Comment by RonnyPfannschmidt** [comment]
will reopen due to gh glitch

**Comment by RonnyPfannschmidt** [comment]
@samdammers its unclear why the gh test action is not running right now, will merge manually later

**Comment by Milind-TW** [comment]
Requesting a new release tag for this change so that we can use the latest version in our pipelines.

**Comment by RonnyPfannschmidt** [comment]
thanks for the ping, i ran out of time when i was at releasign this last

**Pull request merged**
